name: fading_widget_package
description: A package to make easy fading a widget
version: 0.0.1
homepage: https://github.com/Moaaz-Mohammed/FadingAnimation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

